version: '3'
services:
  wyoming-piper:
    extends:
      file: docker-compose.base.yml
      service: wyoming-piper
    build:
      dockerfile: GPU.Dockerfile
    ports:
      - "10200:10200"
    volumes:
      - piper-data:/data
    command: [ "--voice", "en_US-lessac-medium" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  wyoming-whisper:
    extends:
      file: docker-compose.base.yml
      service: wyoming-whisper
    build:
      dockerfile: GPU.Dockerfile
    ports:
      - "10300:10300"
    volumes:
      - whisper-data:/data
    command: [ "--model", "medium-int8", "--language", "en" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  wyoming-openwakeword:
    extends:
      file: docker-compose.base.yml
      service: wyoming-openwakeword
    build:
      dockerfile: GPU.Dockerfile
    ports:
      - "10400:10400"
    volumes:
      - openwakeword-data:/data
    command: [ "--model", "hey_jarvis" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
 openwakeword-data:
 whisper-data:
 piper-data:
  
